### ISSUE TITLE
Fatal exception in StartActivity

### ISSUE THREAD

**Issue by haroonshah2764** [systers/powerup-android#1094]
## Description
There is a fatal exception in StartActivity because width of a view has not been specified. We should fix this.

## Mocks
```
03-29 15:44:56.733 22607-22607/powerup.systers.com.powerup E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: powerup.systers.com.powerup, PID: 22607
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{powerup.systers.com.powerup/powerup.systers.com.StartActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: You must supply a layout_width attribute.
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                              Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: You must supply a layout_width attribute.
```

### Update [Required]
- [ ] Issue is fixed
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by Rimjhim28** [comment]
@haroonshah2764  please provide steps to reproduce the exception.

**Comment by AjaySharvesh3** [comment]
Can I solve this issue? @m-murad @Rimjhim28 @geekanamika

**Comment by Rimjhim28** [comment]
@AjaySharvesh3 The issue is not approved yet.
Moreover, @haroonshah2764 may intend to solve this.

**Comment by haroonshah2764** [comment]
@Rimjhim28 When ever I open the app I get this log
@AjaySharvesh3 I want to work on this.

**Comment by geekanamika** [comment]
@Rimjhim28 I didn't face this issue yet. Can you check on your end too? @haroonshah2764 Make sure your code is updated with the repo. If it still persists, Comment here with steps to solve the issue.

**Comment by Rimjhim28** [comment]
The issue is not valid with latest code changes.
