### ISSUE TITLE
App Crashes in Game Activity

### ISSUE THREAD

**Issue by codingblazer** [systers/powerup-android#329]
It has happened for the second time. The app crashes with the message "Power Up has stopped working" and then app won't start. I was able to recover the logcat from the adb which is attached below.
```02-15 20:40:14.945 23084-23084/? E/linker: warning: unable to get realpath for the library "/data/app/powerup.systers.com.powerup-2/oat/arm64/base.odex". Will use given name.
02-15 20:40:15.791 23084-23084/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: powerup.systers.com.powerup, PID: 23084
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{powerup.systers.com.powerup/powerup.systers.com.GameActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.akexorcist.roundcornerprogressbar.common.BaseRoundCornerProgressBar$SavedState
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                    Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
```
**Fix For the Crash** - The crash is happening because following library is buggy - 

> compile 'com.akexorcist:RoundCornerProgressBar:2.0.3'

It has been reported on lib's issue list many times by other people - [Bug in Lib](https://github.com/akexorcist/Android-RoundCornerProgressBar/issues/57) The logcat for crash is same as this. I think, we should move to some other library.

@chhavip @anubhakushwaha @aanchal07   Can i work on this ?

**Comment by anubhakushwaha** [comment]
@codingblazer What is the alternative you suggest?

**Comment by codingblazer** [comment]
I tried to find alternate library but was unable to find any. I went ahead and implemented the custom Progress Bar by defining custom rounded drawable for progress bar (using layer list). After trying a lot, the final result are as follows -

Earlier                                                                             
![whatsapp image 2017-02-18 at 12 36 00 am](https://cloud.githubusercontent.com/assets/13872065/23079430/e5a84acc-f572-11e6-84fe-5b6a78642945.jpeg)
After
![whatsapp image 2017-02-18 at 12 36 00 am 1](https://cloud.githubusercontent.com/assets/13872065/23079434/e7d74cbc-f572-11e6-978f-f006c9741f12.jpeg)

**Comment by codingblazer** [comment]
@anubhakushwaha Should I send PR for this ? Thanks :-)

**Comment by codingblazer** [comment]
@anubhakushwaha Please review :-)

**Comment by aanchal07** [comment]
@codingblazer We are not using the health and power bars as of now, they are just static progress bars. Once we decide on implementing this feature, you can go ahead with the PR.

**Comment by codingblazer** [comment]
@aanchal07 Yeah that's fine. But should we also defer this crash for now :-)
