### ISSUE TITLE
Not able to resume any scene after restarting the app

### ISSUE THREAD

**Issue by nb2998** [systers/powerup-android#551]
**Steps to reproduce:**
After restarting the app, load game, click on any scene and click on replay.

**Logcat:**
`11-14 19:52:46.587 31259-31259/powerup.systers.com.powerup E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: powerup.systers.com.powerup, PID: 31259
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{powerup.systers.com.powerup/powerup.systers.com.GameActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int powerup.systers.com.datamodel.Scenario.getId()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2762)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2848)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int powerup.systers.com.datamodel.Scenario.getId()' on a null object reference
                                                                                 at powerup.systers.com.GameActivity.onCreate(GameActivity.java:77)
                                                                                 at android.app.Activity.performCreate(Activity.java:6743)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2715)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2848) 
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6334) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
11-14 19:52:46.587 31259-31259/powerup.systers.com.powerup D/AppTracker: App Event: crash`

I would like to work on this. 
@codingblazer @MeepyMay

**Comment by Rimjhim28** [comment]
Hey @nb2998  I think I have reported a similar kind of issue through #500 for the replay button not workin properly and #515 where all the previous karma points, scenarios already played are lost. After solving and merging of these issues I am not sure whether this issue will still exist or not.
@codingblazer 's view could help us here.

**Comment by Divya10** [comment]
Hello,can i work on this issue.

**Comment by MeepyMay** [comment]
Similar to issue #500 so closing this one. Thanks for raising the concern again.
